on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.0

      - name: Build and test
        run: go test -v ./...

      - name: Build binary
        run: go build -o minecraft-controller
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
